[package]
name = "topgun-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TopGun core: CRDTs, HLC, MerkleTree, message schemas"

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
rmp-serde = "1"
rmpv = { version = "1", features = ["with-serde"] }
serde_json = "1"
tracing = "0.1"

[dev-dependencies]
proptest = "1"
