global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'topgun-server'
    static_configs:
      - targets: ['server:9091']
    metrics_path: /metrics

  - job_name: 'topgun-cluster'
    static_configs:
      - targets:
          - 'node-1:9091'
          - 'node-2:9091'
          - 'node-3:9091'
    metrics_path: /metrics
